CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL CHECK (length(trim(title)) > 0),
  done BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO tasks (id, title, done)
VALUES
  (1, 'Learn Express basics', true),
  (2, 'Build a CRUD API', false),
  (3, 'Connect the API to Postgres', false)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('tasks', 'id'), GREATEST((SELECT max(id) FROM tasks), 1));
